# Generated by Django 5.2.4 on 2025-08-03 22:30

import core.account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=225, null=True, unique=True, verbose_name='Email')),
                ('is_email_verified', models.BooleanField(blank=True, default=False, verbose_name='Email Verified?')),
                ('account_type', models.CharField(blank=True, choices=[('super_administrator', 'SUPER_ADMINISTRATOR'), ('staff', 'STAFF'), ('site_user', 'USER')], default='site_user', max_length=20, verbose_name='Account Type')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=50, null=True, verbose_name='Gender')),
                ('is_banned', models.BooleanField(default=False, verbose_name='User account has been banned')),
                ('ban_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='User account ban expiry date')),
                ('ban_duration_in_minutes', models.PositiveIntegerField(default=0, verbose_name='Ban duration in minutes')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Phone Number')),
                ('is_phone_number_verified', models.BooleanField(blank=True, default=False, verbose_name='Phone Number Verified?')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Location (State, Country)')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('objects', core.account.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('refresh', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('access', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Session',
                'verbose_name_plural': 'Account Sessions',
            },
        ),
    ]
