# Generated by Django 5.2.4 on 2026-07-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_dietary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='access',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='refresh',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
