# Generated by Django 5.2.4 on 2026-08-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Key')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('kobo_per_person_per_day', models.PositiveIntegerField(verbose_name='Budget (kobo) per person per day')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Budget Tier',
                'verbose_name_plural': 'Budget Tiers',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PriceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Area Name')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, help_text='Used when a user has not told us where they shop.', verbose_name='Default Area')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Price Area',
                'verbose_name_plural': 'Price Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('aliases', models.JSONField(blank=True, default=list, help_text="Other names the AI or a user might use, e.g. ['ugwu', 'pumpkin leaf']. Matched case-insensitively when costing a meal.", verbose_name='Aliases')),
                ('category', models.CharField(choices=[('staple', 'Staples and swallow'), ('protein', 'Protein'), ('vegetable', 'Vegetables'), ('fruit', 'Fruit'), ('oil', 'Oils and fats'), ('seasoning', 'Seasoning'), ('dairy', 'Dairy and eggs'), ('drink', 'Drinks'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('derica', 'Derica (milk cup)'), ('mudu', 'Mudu'), ('paint', 'Paint bucket'), ('bunch', 'Bunch'), ('piece', 'Piece'), ('bottle', 'Bottle'), ('sachet', 'Sachet'), ('congo', 'Congo')], help_text='The unit every price for this ingredient is quoted in.', max_length=20, verbose_name='Pricing Unit')),
                ('protein_g_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text="Used to answer 'cheapest way to hit my protein today'.", max_digits=8, null=True, verbose_name='Protein (g) per unit')),
                ('kcal_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Energy (kcal) per unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('include_in_prompt', models.BooleanField(default=True, help_text='The AI may only use ingredients from this catalogue, so anything excluded here cannot appear in a costed plan.', verbose_name='Include in AI catalogue')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'include_in_prompt'], name='pricing_ing_is_acti_3509f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('derica', 'Derica (milk cup)'), ('mudu', 'Mudu'), ('paint', 'Paint bucket'), ('bunch', 'Bunch'), ('piece', 'Piece'), ('bottle', 'Bottle'), ('sachet', 'Sachet'), ('congo', 'Congo')], max_length=20, verbose_name='Unit')),
                ('price_kobo', models.PositiveIntegerField(verbose_name='Price (kobo)')),
                ('observed_on', models.DateField(db_index=True, help_text='The date this price was true, not the date it was recorded.', verbose_name='Observed On')),
                ('source', models.CharField(choices=[('admin_survey', 'Market survey'), ('user', 'User reported'), ('rtfp', 'World Bank RTFP'), ('estimate', 'Unverified estimate')], default='admin_survey', max_length=20, verbose_name='Source')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='pricing.pricearea', verbose_name='Area')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='pricing.ingredient', verbose_name='Ingredient')),
            ],
            options={
                'verbose_name': 'Price Observation',
                'verbose_name_plural': 'Price Observations',
                'ordering': ['-observed_on'],
                'indexes': [models.Index(fields=['ingredient', 'area', '-observed_on'], name='pricing_pri_ingredi_39dc83_idx'), models.Index(fields=['area', '-observed_on'], name='pricing_pri_area_id_925687_idx')],
            },
        ),
    ]
