# Generated by Django 5.2.4 on 2025-09-19 00:17

import core.file_storage.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=1000, upload_to=core.file_storage.models.upload_format_file, verbose_name='Content')),
                ('purpose', models.CharField(choices=[('avatar', 'AVATAR'), ('food image', 'FOOD_IMAGE')], max_length=100, verbose_name='Purpose of Uploading')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='File MIME Type')),
                ('upload_session_id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, verbose_name='File Upload Session ID')),
                ('currently_under_processing', models.BooleanField(blank=True, default=False, verbose_name='Is this file currently under processing')),
                ('original_name', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Original File Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
