# Generated by Django 5.2.4 on 2026-01-13 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField(help_text='Start date of the week (Monday)', verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(help_text='End date of the week (Sunday)', verbose_name='Week End Date')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of the data used to generate recommendations', null=True, verbose_name='Input Data')),
                ('health_report', models.TextField(blank=True, help_text='AI-generated weekly health report', null=True, verbose_name='Health Report')),
                ('recommendations', models.JSONField(blank=True, default=dict, help_text='AI-generated weekly recommendations', null=True, verbose_name='Recommendations')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Processing', 'PROCESSING'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('is_mock_data', models.BooleanField(default=False, verbose_name='Is Mock Data')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notification Sent At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Recommendation Owner')),
            ],
            options={
                'verbose_name': 'Weekly Recommendation',
                'verbose_name_plural': 'Weekly Recommendations',
                'ordering': ['-week_start_date'],
                'unique_together': {('owner', 'week_start_date')},
            },
        ),
    ]
