# Generated by Django 5.2.4 on 2026-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Has User Read Notification?'),
        ),
    ]
