# Generated by Django 5.2.4 on 2026-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_weeklyrecommendation_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='priority_actions',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated priority actions that user should take', null=True, verbose_name='Priority Actions'),
        ),
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='weekly_goals',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated weekly health goals', null=True, verbose_name='Weekly Goals'),
        ),
    ]
