"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.utils.timezone import timedelta
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from core.utils import enums
from config.celery.queue import CeleryQueue
from celery.schedules import crontab
import sentry_sdk

from .. import env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

PRODUCTION = env.bool("PRODUCTION", False)
USE_MEMORY_DATABASE = env.bool("USE_MEMORY_DATABASE", True)
USING_MANAGED_STORAGE = env.bool("USING_MANAGED_STORAGE", False)

# Gemini AI Configuration
GEMINI_API_KEY = env.str("GEMINI_API_KEY", "")
GEMINI_MODEL = env.str("GEMINI_MODEL", "gemini-1.5-flash")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY", 'django-insecure-cbu$=!&(o-kbl#d@($!(s--mpdoeoy#ht^__ejmjt@cq5q=n&#'
)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=[
        "*",
    ],
)


# Application definition

INSTALLED_APPS = [
    "daphne",
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_celery_beat",
    "channels"
]

CORE_APPS = [
    "core.account.apps.AccountConfig",
    "core.file_storage.apps.FileStorageConfig",
    "core.results.apps.ResultsConfig",
    "core.analytics.apps.AnalyticsConfig",
    "core.utils.apps.UtilsConfig",
    "core.recommendations.apps.RecommendationsConfig",
    "core.websocket.apps.WebsocketConfig",
    "core.system.apps.SystemConfig",
    "core.meal_plan.apps.MealPlanConfig",
    "core.cooking.apps.CookingConfig",
    "core.billing.apps.BillingConfig",
    "core.pricing.apps.PricingConfig",
]

INSTALLED_APPS += CORE_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['core/utils/helpers/email/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The product is Nigeria-only, and several rules are keyed to a calendar day:
# the daily photo-analysis allowance, `current_billing_month`, and the day
# grouping in the analytics helpers. On UTC the day rolled over at 01:00 WAT,
# so a user logging dinner at 00:30 had it counted against the next day.
TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

API_VERSION = env.int("API_VERSION", default=1)
AUTH_USER_MODEL = "account.Account"

# CORS
CORS_ALLOW_ALL_ORIGINS = env.bool(
    "CORS_ALLOW_ALL_ORIGINS", True
)
CORS_ALLOWED_ORIGINS = env.list(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        default=["http://localhost:5173"],
    )

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        # "core.utils.permissions.EnforceAccountBan",
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/minute",
        "user": "120/minute",
        # Scoped rates for endpoints where an unlimited request loop is the attack.
        # `otp_verify` is the important one: a 6 digit code is guessable in minutes
        # at full speed, and the OTP is what authorises a password change.
        "otp_verify": "10/hour",
        "otp_request": "5/hour",
        "login": "10/minute",
        "payment_init": "10/hour",
        # Each analysis is a paid Gemini vision call. The daily allowance in
        # `BillingPlan` is the business rule; this stops a request loop before
        # it reaches the database at all.
        "food_analysis": "20/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.utils.exceptions.exceptions.custom_exception_handler",
}


# Schema Spectacular Generator
SPECTACULAR_SETTINGS = {
    "TITLE": "NutriLens API",
    "DESCRIPTION": "AI platform for healthy feeding",
    "VERSION": f"V{API_VERSION}",
    "SERVE_INCLUDE_SCHEMA": False,
        "ENUM_NAME_OVERRIDES": {
        "AccountTypeEnum": enums.UserAccountType.choices(),
        "GenderTypeEnum": enums.UserGenderType.choices(),
    }
}


UNFOLD = {
    "SITE_TITLE": "NutriLens Backend",
    "SITE_DESCRIPTION": "AI platform for healthy feeding",
    "SITE_HEADER": "NutriLens",
    "SHOW_HISTORY": True,
    "SIDEBAR": {
        "show_search": True,
        "show-all_applications": True,
        "navigation": [
            {
                "title": _("Users & Session"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:account_account_changelist"),
                    },
                    {
                        "title": _("Sessions"),
                        "icon": "fingerprint",
                        "link": reverse_lazy("admin:account_usersession_changelist"),
                    },
                ],
            },
            {
                "title": _("File Storage"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Files"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:file_storage_filemodel_changelist"),
                    },
                ]
            },
            {
                "title": _("Results"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Food Analysis"),
                        "icon": "report",
                        "link": reverse_lazy("admin:results_foodanalysis_changelist"),
                    },
                    {
                        "title": _("Detected Food"),
                        "icon": "food_bank",
                        "link": reverse_lazy("admin:results_detectedfood_changelist"),
                    }
                ]
            },
            {
                "title": _("Recommendations"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Weekly Recommendations"),
                        "icon": "food_bank",
                        "link": reverse_lazy("admin:recommendations_weeklyrecommendation_changelist"),
                    },
                ]
            },
        ]
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

CELERY_BROKER = env.str("CELERY_BROKER")
CELERY_BROKER_URL = CELERY_BROKER
CELERY_RESULT_BACKEND = env.str("CELERY_BACKEND")
CELERY_TIMEZONE = env.str("CELERY_TIMEZONE", default="UTC")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_QUEUES = CeleryQueue.queues()
CELERY_TASK_DEFAULT_QUEUE = "email-notification"

CELERY_BEAT_SCHEDULE = {
    "generate-weekly-recommendations": {
        "task": "core.recommendations.tasks.generate_weekly_recommendations_for_all_users",
        "schedule": crontab(hour=6, minute=0, day_of_week=1),
        "options": {"queue": "recommendations"},
    },
    "send-subscription-renewal-reminders": {
        "task": "core.billing.tasks.send_subscription_renewal_reminders",
        "schedule": crontab(hour=8, minute=0),
        "options": {"queue": "email-notification"},
    },
    "expire-subscription-grace-periods": {
        "task": "core.billing.tasks.expire_subscription_grace_periods",
        "schedule": crontab(minute=0),
        "options": {"queue": "email-notification"},
    },
    "expire-lapsed-subscriptions": {
        "task": "core.billing.tasks.expire_lapsed_subscriptions",
        "schedule": crontab(minute=15),
        "options": {"queue": "email-notification"},
    },
}


REDIS_HOST = env.str("REDIS_HOST", default="localhost")
REDIS_PORT = env.int("REDIS_PORT", default=6379)
REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"
REDIS_PASSWORD = env.str("REDIS_PASSWORD", default="")

# if REDIS_PASSWORD:
#     REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
# else:
#     REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

SIGNUP_OTP_TTL_SECONDS = env.int("SIGNUP_OTP_TTL_SECONDS", default=300)
PASSWORD_RESET_OTP_TTL_SECONDS = env.int("PASSWORD_RESET_OTP_TTL_SECONDS", default=300)
OTP_VERIFIED_TTL_SECONDS = env.int("OTP_VERIFIED_TTL_SECONDS", default=300)
CACHE_TTL = env.int("CACHE_TTL", default=300)


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

sentry_sdk.init(
    dsn="https://1dee5c434e783fffa8db4a619178d1ff@o4511473649057792.ingest.de.sentry.io/4511473672126544",
    send_default_pii=True,
    enable_logs=True,
    traces_sample_rate=1.0,
    profile_session_sample_rate=1.0,
    profile_lifecycle="trace",
)



# Email settings
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="***")
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
RESEND_API_KEY = env.str("RESEND_API_KEY", default="***")
FEEDBACK_RECIPIENT_EMAIL = env.str("FEEDBACK_RECIPIENT_EMAIL", default="temedia005@gmail.com")




# managed storage configurations
if USING_MANAGED_STORAGE:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

    AWS_ACCESS_KEY_ID = env.str("DJANGO_AWS_ACCESS_KEY_ID", "*****")
    AWS_SECRET_ACCESS_KEY = env.str("DJANGO_AWS_SECRET_ACCESS_KEY", "*****")
    AWS_STORAGE_BUCKET_NAME = env.str("DJANGO_AWS_STORAGE_BUCKET_NAME", "*****")

    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_REGION_NAME = env.str("DJANGO_AWS_S3_REGION_NAME", "lon1")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_DEFAULT_ACL = "public-read"
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_ENDPOINT_URL = "https://lon1.digitaloceanspaces.com"
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.lon1.digitaloceanspaces.com"
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

    STATIC_LOCATION = "static"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/"

    PUBLIC_MEDIA_LOCATION = "media"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/"


GEMINI_API_KEY = env.str("GEMINI_API_KEY", default="**********")
GEMINI_MODEL = env.str("GEMINI_MODEL", default="gemini-2.0-flash")

# Mock AI responses are a local-development aid only. Serving invented nutrition
# data to a real user is worse than an honest failure, so this defaults off and
# must be switched on explicitly. It also gates the `use_mock` request field,
# which is client-supplied and would otherwise be a free-analysis hole in prod.
ALLOW_MOCK_AI = env.bool("ALLOW_MOCK_AI", default=False)

USE_DOCS = env.bool("USE_DOCS", False)

# Paystack billing configuration
PAYSTACK_SECRET_KEY = env.str("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = env.str("PAYSTACK_PUBLIC_KEY", default="")
PAYSTACK_BASE_URL = env.str("PAYSTACK_BASE_URL", default="https://api.paystack.co")
PAYSTACK_PLUS_PLAN_CODE = env.str("PAYSTACK_PLUS_PLAN_CODE", default="")
PAYSTACK_PRO_PLAN_CODE = env.str("PAYSTACK_PRO_PLAN_CODE", default="")
FRONTEND_BASE_URL = env.str("FRONTEND_BASE_URL", default="http://localhost:5173")
