# Generated by Django 5.2.4 on 2026-06-17 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField(help_text='The Monday of the week this meal plan covers', verbose_name='Week Start Date')),
                ('budget_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('flexible', 'Flexible')], default='medium', max_length=20, verbose_name='Budget Level')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether this plan was generated by AI', verbose_name='AI Generated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Plan Owner')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-week_start_date'],
                'unique_together': {('owner', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, verbose_name='Day')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20, verbose_name='Meal Type')),
                ('food_name', models.CharField(max_length=200, verbose_name='Food Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prep Time (minutes)')),
                ('health_notes', models.TextField(blank=True, default='', verbose_name='Health Notes')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI Generated')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meal_plan.mealplan', verbose_name='Meal Plan')),
            ],
            options={
                'verbose_name': 'Meal Entry',
                'verbose_name_plural': 'Meal Entries',
                'ordering': ['day', 'meal_type'],
            },
        ),
    ]
