# Generated by Django 5.2.4 on 2026-08-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='estimated_cost_kobo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Cost (kobo)'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, help_text='Costable breakdown as [{name, qty, unit}]. This is what makes a budget real — without quantities there is nothing to multiply by a price.', verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='budget_kobo',
            field=models.PositiveIntegerField(blank=True, help_text='What the owner has to spend on food this week, for the whole household. Set from the budget tier unless they entered their own amount.', null=True, verbose_name='Weekly Budget (kobo)'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='estimated_cost_kobo',
            field=models.PositiveIntegerField(blank=True, help_text="Recomputed from our own price table, never taken from the AI's arithmetic. Frozen at generation time so a saved plan does not change value later.", null=True, verbose_name='Estimated Cost (kobo)'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='household_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many people this plan feeds. Budgets scale with it.', verbose_name='Household Size'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_custom_budget',
            field=models.BooleanField(default=False, help_text='True when the owner typed an amount instead of picking a tier.', verbose_name='Custom Budget'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='price_area',
            field=models.ForeignKey(blank=True, help_text="Which city's prices this plan was costed against.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='pricing.pricearea', verbose_name='Price Area'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='priced_at',
            field=models.DateTimeField(blank=True, help_text='When the cost was last computed, so staleness can be shown.', null=True, verbose_name='Priced At'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='unpriced_items',
            field=models.JSONField(blank=True, default=list, help_text='Ingredients the AI used that are not in the priced catalogue.', verbose_name='Unpriced Items'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('flexible', 'Flexible')], default='medium', help_text='Preset used when the owner did not name their own figure.', max_length=20, verbose_name='Budget Level'),
        ),
    ]
