from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.utils.mixins import BaseModelMixin


DAY_CHOICES = [
    ("monday", "Monday"),
    ("tuesday", "Tuesday"),
    ("wednesday", "Wednesday"),
    ("thursday", "Thursday"),
    ("friday", "Friday"),
    ("saturday", "Saturday"),
    ("sunday", "Sunday"),
]

MEAL_TYPE_CHOICES = [
    ("breakfast", "Breakfast"),
    ("lunch", "Lunch"),
    ("dinner", "Dinner"),
    ("snack", "Snack"),
]

BUDGET_LEVEL_CHOICES = [
    ("low", "Low"),
    ("medium", "Medium"),
    ("flexible", "Flexible"),
]


class MealPlan(BaseModelMixin):
    owner = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.CASCADE,
        related_name="meal_plans",
        null=False,
        blank=False,
        verbose_name=_("Plan Owner"),
    )
    week_start_date = models.DateField(
        _("Week Start Date"),
        null=False,
        blank=False,
        help_text=_("The Monday of the week this meal plan covers"),
    )
    budget_level = models.CharField(
        _("Budget Level"),
        max_length=20,
        choices=BUDGET_LEVEL_CHOICES,
        default="medium",
    )
    is_ai_generated = models.BooleanField(
        _("AI Generated"),
        default=False,
        help_text=_("Whether this plan was generated by AI"),
    )

    class Meta:
        verbose_name = _("Meal Plan")
        verbose_name_plural = _("Meal Plans")
        ordering = ["-week_start_date"]
        unique_together = [("owner", "week_start_date")]

    def __str__(self):
        return f"{self.owner.first_name}'s plan - Week of {self.week_start_date}"


class MealEntry(BaseModelMixin):
    meal_plan = models.ForeignKey(
        to=MealPlan,
        on_delete=models.CASCADE,
        related_name="entries",
        null=False,
        blank=False,
        verbose_name=_("Meal Plan"),
    )
    day = models.CharField(
        _("Day"),
        max_length=20,
        choices=DAY_CHOICES,
    )
    meal_type = models.CharField(
        _("Meal Type"),
        max_length=20,
        choices=MEAL_TYPE_CHOICES,
    )
    food_name = models.CharField(
        _("Food Name"),
        max_length=200,
    )
    description = models.TextField(
        _("Description"),
        blank=True,
        default="",
    )
    prep_time_minutes = models.PositiveIntegerField(
        _("Prep Time (minutes)"),
        null=True,
        blank=True,
    )
    health_notes = models.TextField(
        _("Health Notes"),
        blank=True,
        default="",
    )
    is_ai_generated = models.BooleanField(
        _("AI Generated"),
        default=False,
    )

    class Meta:
        verbose_name = _("Meal Entry")
        verbose_name_plural = _("Meal Entries")
        ordering = ["day", "meal_type"]

    def __str__(self):
        return f"{self.day} - {self.meal_type}: {self.food_name}"
