# Generated by Django 5.2.4 on 2026-07-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusageledger',
            new_name='billing_aiu_owner_i_d21d7d_idx',
            old_name='billing_ai_owner__713ad1_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusageledger',
            new_name='billing_aiu_owner_i_39d8ba_idx',
            old_name='billing_ai_owner__23f63f_idx',
        ),
    ]
