# Generated by Django 5.2.4 on 2026-07-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_demo_invites_feature_entitlements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureentitlement',
            new_name='billing_fea_owner_i_6eec69_idx',
            old_name='billing_fea_owner_i_3aa562_idx',
        ),
    ]
