# Generated by Django 5.2.4 on 2026-08-12 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_billing_fea_owner_i_3aa562_idx_billing_fea_owner_i_6eec69_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='analysis_daily_limit',
            field=models.PositiveIntegerField(default=3, help_text="Photo analyses allowed per calendar day. Daily rather than monthly so users never hoard their allowance, and a runaway loop is capped at a day's worth instead of a month's.", verbose_name='Daily Photo Analysis Limit'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='analysis_monthly_limit',
            field=models.PositiveIntegerField(default=45, help_text='Abuse ceiling for sustained scripted use. Set to 0 to disable the monthly check and rely on the daily limit alone.', verbose_name='Monthly Photo Analysis Backstop'),
        ),
        migrations.AlterField(
            model_name='aiusageledger',
            name='feature_type',
            field=models.CharField(choices=[('meal_plan', 'AI Meal Plan'), ('meal_plan_day', 'AI Day Meal Plan'), ('cooking_guide', 'AI Cooking Guide'), ('food_analysis', 'Food Photo Analysis')], max_length=40, verbose_name='Feature Type'),
        ),
        migrations.AddIndex(
            model_name='aiusageledger',
            index=models.Index(fields=['owner', 'feature_type', 'date_added'], name='billing_aiu_owner_i_e9ea5a_idx'),
        ),
    ]
